"""empty message

Revision ID: db2f6e72b6da
Revises: 
Create Date: 2018-08-20 10:49:44.465035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2f6e72b6da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('updateAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('passwordresettoken', sa.String(length=250), nullable=True),
    sa.Column('passwordresetexpires', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('facebook', sa.String(length=250), nullable=True),
    sa.Column('google', sa.String(length=250), nullable=True),
    sa.Column('linkin', sa.String(length=250), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('updateAt', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('KYC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=125), nullable=False),
    sa.Column('phone', sa.String(length=125), nullable=False),
    sa.Column('id_verify', sa.String(length=125), nullable=False),
    sa.Column('image_front_verify', sa.String(length=125), nullable=False),
    sa.Column('image_selfie_verify', sa.String(length=125), nullable=False),
    sa.Column('image_with_verify', sa.String(length=125), nullable=False),
    sa.Column('image_alternative', sa.String(length=125), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('updateAt', sa.DateTime(), nullable=False),
    sa.Column('field_error', sa.String(length=125), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission', sa.String(length=125), nullable=False),
    sa.Column('permissionID', sa.String(length=125), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('updateAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permissionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Permission')
    op.drop_table('KYC')
    op.drop_table('User')
    op.drop_table('Role')
    # ### end Alembic commands ###
